name: Generate openAPI upload to S3

on:
  push:
    branches: [main]

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - use: actions/checkout@v4
      - names: setup go
        use: actions/go-setup@v4
        with:
          go version: "1.2.1"
      - names: install swag
        run: |
          go install github.com/swaggo/swag/cmd/swag@latest
          echo "$GOPATH/bin" >> "$GITHUB_PATH"
      - name: generate openapi by swagger
        run: |
          swag init -g ./cmd/main.go -o ./docs
      - name: openapi.yml upload to S3
        uses: jakejarvis/s3-sync-action@v0.6.0
        with:
          args: --acl public-read --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.OPENAPI_S3_BUCKET }} # e.g. my-bucket/openapi
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-northeast-1
          SOURCE_DIR: "docs"
